### ISSUE TITLE
support for other dataset yelp and movielens 

### ISSUE THREAD

**Issue by wondergo2017** [FeiGSSS/DySAT_pytorch#1]
Can you add support for dataset yelp and movielens？ it really helps. Thank you !

**Comment by FeiGSSS** [comment]
Hi,
The main function of this implementation supports any datasets as long as they are preprocessed into the same format. The official implementation has processing codes for the other two datasets[https://github.com/aravindsankar28/DySAT/tree/master/raw_data](url). You can add their raw data and preprocessing codes to this implementation. 

> Can you add support for dataset yelp and movielens？ it really helps. Thank you !
