### ISSUE TITLE
the problem of results

### ISSUE THREAD

**Issue by trytodoit227** [FeiGSSS/DySAT_pytorch#6]
Since you mention that the  results are inconsistent with official results (better than that), could you please tell me whether the official results are in Table 2?

**Comment by FeiGSSS** [comment]
> Since you mention that the results are inconsistent with official results (better than that), could you please tell me whether the official results are in Table 2?

It has been a long time since I pushed those codes. But, yes, the `official results` I mentioned are the results (only for dataset Enron) in Table2 in the original paper.

**Comment by trytodoit227** [comment]
Thank  you
